### ISSUE TITLE
Support absolute path in `files` setting

### ISSUE THREAD

**Issue by MartinAltmayerTNG** [EnricoMi/publish-unit-test-result-action#119]
I would like to collect test results somewhere in /tmp (so that I don't modify the checked out source tree that is the current working directory). Unfortunately, this fails with the following error:

```
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 202, in <module>
    main(settings)
  File "/action/publish_unit_test_results.py", line 52, in main
    files = [str(file) for file in pathlib.Path().glob(settings.files_glob)]
  File "/action/publish_unit_test_results.py", line 52, in <listcomp>
    files = [str(file) for file in pathlib.Path().glob(settings.files_glob)]
  File "/usr/local/lib/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
```

Here is my configuration:
```
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.12
        # run even if tests failed
        if: always()
        with:
          files: /tmp/test-reports/**/*.xml
```

**Comment by EnricoMi** [comment]
Good point, this is a limitation of the used glob library. #121 fixes this, among other improvements.

**Comment by EnricoMi** [comment]
This has been released and is available as `uses: EnricoMi/publish-unit-test-result-action@v1`.

Thanks for raising this issue.

**Comment by sjkingo** [comment]
Just checking `uses: EnricoMi/publish-unit-test-result-action@v1` definitely should fix this? I am using this:

```
        with:
          files: /github/workspace/pytest.xml
```

And still getting this:

```
 Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 199, in <module>
    main(settings)
  File "/action/publish_unit_test_results.py", line 51, in main
    files = [str(file) for file in pathlib.Path().glob(settings.files_glob)]
  File "/action/publish_unit_test_results.py", line 51, in <listcomp>
    files = [str(file) for file in pathlib.Path().glob(settings.files_glob)]
  File "/usr/local/lib/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
```

My use case is the previous build step runs tests inside a Docker container, which stores the xunit result file in the mapped `/github/workspace` volume. I need to publish it from there.

**Comment by EnricoMi** [comment]
Sorry, I had to revert that feature as it introduced some regression: #124

**Comment by sjkingo** [comment]
Thanks for the update.

**Comment by EnricoMi** [comment]
The bug has been resolved in #126 and released again.

**Comment by invalidred** [comment]
Hey @EnricoMi is absolute file path supported? I have the following config with my test results stored in `/tmp/e2e-artifacts/results.xml`

```
      - name: run e2e test
        env:
          LOGIN_SECRET: ${{secrets.LOGIN_SECRET}}
        run: |
          docker run -t  \
          -e LOGIN_SECRET \
          -e CI=true \
          -v /tmp/e2e-artifacts/:/app/playwright-report/ \
          -v /tmp/e2e-artifacts/:/app/test-results/ \
          ${{ env.TEST_TAG }}

      - name: upload e2e artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: e2e-artifact
          path: /tmp/e2e-artifacts/
          retention-days: 5

      - name: check contents of /tmp
        run: ls /tmp/e2e-artifacts/

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
             /tmp/e2e-artifacts/results.xml

```

According the the ` ls /tmp/e2e-artifacts/` I see the artifact file does exists

```
data
index.html
results.xml
src-pages-me-booking-links-__tests__-create-booking-link-Create-booking-link-Create-simple-booking-link--chromium
src-pages-me-calendars-__tests__-calendar-Calendar-operations-create-calendar-update-delete-calendar-chromium
```

However I see the following when the `Publish Unit Test Results` runs

> Warning: Could not find any files for /tmp/e2e-artifacts/results.xml


I was wondering if absolute paths are supported.

Thank you for your wonderful GH action.

**Comment by EnricoMi** [comment]
I think the issue is that `uses: EnricoMi/publish-unit-test-result-action@v1` runs the action in a docker container which mounts the current working directory but nothing beyond.

The following should work:
```
      - name: Move artifacts from /tmp into CWD
        run: mv -v /tmp/e2e-artifacts ./

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
             ./e2e-artifacts/results.xml
```
