### ISSUE TITLE
Make action work on all OS

### ISSUE THREAD

**Issue by joshrlesch** [EnricoMi/publish-unit-test-result-action#19]
This action is only supported on Linux since its container based. Is it possible to support multiple OS for use with `self-hosted` runners like internal Macs.

**Comment by EnricoMi** [comment]
That is a good question. So I think the only alternative to a container action would be the [Composite run steps](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action). That should work on [Linux, MacOS, Windows](https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions). Do you agree?

I presume you can mix operating systems and self-hosted with GitHub-hosted jobs in the same workflow. For the time being, you could then run your tests on your self-hosted MacOS runners and upload the test result files as artifacts. In a separate job in the same workflow you can then publish the unit test results using a GitHub-hosted Linux based job:

```
jobs:
  test:
    runs-on: [self-hosted, macOs]
  ...

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@master
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "artifacts/**/*.xml"
```

Is that an option for you?

**Comment by joshrlesch** [comment]
Thanks for the reply! I think that is a decent alternative for the time being. Since you marked this with a `enhancement` label, do you think it's possible to add support for multi OS's? I know there is a limitation by GH for this to work out of the box, but if there is a change that would be great!

**Comment by EnricoMi** [comment]
I'll try the 'composite run steps' action. I don't see why this shouldn't work. And you are right, having this run on multiple OS would be great.

**Comment by EnricoMi** [comment]
Hi,

I have turned this action into a "composite run steps action".

Please give it a try:

```
uses: EnricoMi/publish-unit-test-result-action@branch-composite-action
```

You need to add a python step before this action:

```
- name: Setup Python
  uses: actions/setup-python@v2
  with:
    python-version: 3
```

**Comment by EnricoMi** [comment]
@joshrlesch have you had a chance to try the "composite run steps action" on MacOS?

**Comment by joshrlesch** [comment]
> @joshrlesch have you had a chance to try the "composite run steps action" on MacOS?

I kinda have. I tried it quick, but ran into python environment errors on our Macs. I wasn't able to look into it much further, but still plan on getting to this sometime.

**Comment by EnricoMi** [comment]
Do you run this on a public github? Then I could look into the action's output.

**Comment by joshrlesch** [comment]
> Do you run this on a public github? Then I could look into the action's output.

Nope, this is a private company repo. Hopefully I can get to this later this week.

**Comment by EnricoMi** [comment]
Alright. Did you see that you need to add a Python step before this action now? See https://github.com/EnricoMi/publish-unit-test-result-action/tree/branch-composite-action#using-this-action.

**Comment by jonathanmedd** [comment]
I'd be interested in running this on `windows-latest`. I tried the above with:

```
- name: Setup Python
  uses: actions/setup-python@v2
  with:
    python-version: 3

- name: Publish Unit Test Results
  uses: EnricoMi/publish-unit-test-result-action@branch-composite-action
  if: always()
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    files: tools\testResults.xml
```
 but got the following error:

```
Install Python dependencies
  Collecting pip
    Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
  Installing collected packages: pip
    Attempting uninstall: pip
      Found existing installation: pip 21.0.1
      Uninstalling pip-21.0.1:
        Successfully uninstalled pip-21.0.1
  Successfully installed pip-21.0.1
  Collecting virtualenv
    Downloading virtualenv-20.4.2-py2.py3-none-any.whl (7.2 MB)
  Collecting distlib<1,>=0.3.1
    Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
  Collecting filelock<4,>=3.0.0
    Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
  Collecting appdirs<2,>=1.4.3
    Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
  Collecting six<2,>=1.9.0
    Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
  Installing collected packages: six, filelock, distlib, appdirs, virtualenv
  Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 six-1.15.0 virtualenv-20.4.2
  created virtual environment CPython3.9.1.final.0-64 in 3255ms
    creator CPython3Windows(dest=D:\a\BricksetModule\BricksetModule\venv, clear=False, no_vcs_ignore=False, global=False)
    seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\runneradmin\AppData\Local\pypa\virtualenv)
      added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
    activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
  D:\a\_temp\9385afb1-1783-4090-9189-59028d9e99d9.sh: line 5: venv/bin/activate: No such file or directory
  Error: Process completed with exit code 1.
```

Were you expecting it to work on `windows-latest` yet?

**Comment by EnricoMi** [comment]
You can use the action from this branch:

    uses: EnricoMi/publish-unit-test-result-action@branch-composite-action-win

Be reminded this is just a development branch.

**Comment by EnricoMi** [comment]
@joshrlesch I have tested the composite action on [Mac OS X (10.15.7)](https://github.com/EnricoMi/python/pull/9/checks?check_run_id=1909335485#step:6:83) and it works.

**Comment by jonathanmedd** [comment]
@EnricoMi Tested fine for me on `windows-latest`

**Comment by wildmichael** [comment]
@EnricoMi The `composite-action-win` branch works fine on `windows-latest`, but currently fails on `ubuntu-latest`. The branch `composite-action` shows the exact opposite behavior. Any chance of getting both to work?

**Comment by EnricoMi** [comment]
@joshrlesch @jonathanmedd @wildmichael This action is not available as a composite action from `master` branch. Please give it a try:

```yaml
- name: Publish Unit Test Results
  uses: EnricoMi/publish-unit-test-result-action/composite@master
  if: always()
  with:
    files: test-results/**/*.xml
```

Note that `master` is a development branch and may break any time, so do not use in production.

This will be released soon and will be available via `@v1` then.
