### ISSUE TITLE
Invalid format with Jest coverage

### ISSUE THREAD

**Issue by sniperadmin** [EnricoMi/publish-unit-test-result-action#217]
### Issue Details
Pops up an `invalid format`
![image](https://user-images.githubusercontent.com/24525973/151775704-000cc5fd-7051-42f6-9aee-6e845545a4ae.png)

Here is the the output comments in my PR
![image](https://user-images.githubusercontent.com/24525973/151776133-d404a08f-644b-418e-b737-206fe0a5e4af.png)

For the Yaml commands:
```yaml
name: CI Linter & Coverage

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: |
          npm ci --prefer-offline --no-audit
          npm install typescript

      - name: Run linter 👀
        run: npm run lint

      - name: Run tests 🧪
        run: npm run test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: coverage/**/*.xml

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "./coverage/clover.xml"
          threshold_alert: 80
          threshold_warning: 85
```
