### ISSUE TITLE
files not found when using with a matrix strategy

### ISSUE THREAD

**Issue by uli-f** [EnricoMi/publish-unit-test-result-action#235]
I experience difficulties using the Github Action `Publish Unit Test Results` with our yaml file that uses a matrix strategy.

It works **fine** with the following config:
```
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '17' ]
    name: Build and Test Java ${{ matrix.Java }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build with gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Upload JUnit Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: JUnit test results (Java ${{ matrix.java }})
        path: build/test-results/test

publish-test-results:
    name: "Publish JUnit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: 'artifacts/JUnit test results (Java 17)/TEST-*.xml'
          check_name: "JUnit Test Results"
          comment_mode: create new
          test_changes_limit: 30
```

However, this config limits the files of publish-unit-test-result-action@v1 to a particular path:
`files: artifacts/JUnit test results (Java 17)/TEST-*.xml`

I then switch to a path with a `**` pattern so that the output of different build environments in a matrix strategy is picked up:
```
- name: Publish Unit Test Results
  uses: EnricoMi/publish-unit-test-result-action@v1
  with:
    files: artifacts/**/TEST-*.xml
    check_name: "JUnit Test Results"
    comment_mode: create new
    test_changes_limit: 30
```
Once I've switched to `files: artifacts/**/TEST-*.xml` I get the following output when running the workflow:
```
Download artifacts
Run actions/download-artifact@v3
  with:
    path: artifacts
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
starting download of artifact JUnit_test_results_(Java_17) : 1/1
Total number of files that will be downloaded: 7
There were 1 artifacts downloaded
Artifact JUnit_test_results_(Java_17) was downloaded to /home/runner/work/XXX/XXX/artifacts/JUnit test results (Java 17)
Artifact download has finished successfully

Display structure of downloaded files
-1s
Run ls -R
.:
JUnit_test_results_(Java_17)

./JUnit_test_results_(Java_17):
TEST-y.y.y.y.xml
TEST-y.y.y.y.xml
TEST-y.y.y.y.xml
TEST-y.y.y.y.xml
binary

./JUnit_test_results_(Java_17)/binary:
output.bin
output.bin.idx
results.bin

Echo download path
-1s
Run echo /home/runner/work/XXX/XXX/artifacts
/home/runner/work/XXX/XXX/artifacts

Publish Unit Test Results
Run EnricoMi/publish-unit-test-result-action@v1
/usr/bin/docker run --name ghcrioenricomipublishunittestresultactionv131_7242ff --label 29a95e --workdir /github/workspace --rm -e INPUT_FILES -e INPUT_CHECK_NAME -e INPUT_COMMENT_MODE -e INPUT_TEST_CHANGES_LIMIT -e INPUT_GITHUB_TOKEN -e INPUT_GITHUB_RETRIES -e INPUT_COMMIT -e INPUT_COMMENT_TITLE -e INPUT_FAIL_ON -e INPUT_TIME_UNIT -e INPUT_REPORT_INDIVIDUAL_RUNS -e INPUT_DEDUPLICATE_CLASSES_BY_FILE_NAME -e INPUT_IGNORE_RUNS -e INPUT_HIDE_COMMENTS -e INPUT_COMMENT_ON_PR -e INPUT_COMPARE_TO_EARLIER_COMMIT -e INPUT_PULL_REQUEST_BUILD -e INPUT_EVENT_FILE -e INPUT_EVENT_NAME -e INPUT_CHECK_RUN_ANNOTATIONS -e INPUT_CHECK_RUN_ANNOTATIONS_BRANCH -e INPUT_SECONDS_BETWEEN_GITHUB_READS -e INPUT_SECONDS_BETWEEN_GITHUB_WRITES -e INPUT_JSON_FILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/XXX/XXX":"/github/workspace" ghcr.io/enricomi/publish-unit-test-result-action:v1.31
2022-03-11 04:32:26 +0000 - publish - WARNING - Could not find any files for artifacts/**/Test-*.xml
2022-03-11 04:32:26 +0000 - publish -  INFO - publishing neutral results for commit f7bef62ced6ce6a865c81970a90d7ddecd04b9eb
2022-03-11 04:32:28 +0000 - publish -  INFO - created check https://github.com/XXX/XXX/runs/5506374528
2022-03-11 04:32:30 +0000 - publish -  INFO - creating comment
2022-03-11 04:32:34 +0000 - publish -  INFO - hiding unit test result comment IC_kwDOE9QET84_dvqC
Warning: Could not find any files for artifacts/**/Test-*.xml
```

**Comment by EnricoMi** [comment]
Is this in a private repository?

**Comment by EnricoMi** [comment]
Can you try the following, please?

    files: "artifacts/**/TEST-*.xml"

and

    files: "artifacts/*/TEST-*.xml"

and

    files: "artifacts/**/*.xml"

**Comment by EnricoMi** [comment]
Maybe `**` has a problem with the whitespaces in the path, can you also try to add this step before the publish action, please?

```yaml
- run: |
    mv -v "artifacts/JUnit test results (Java 17)" "artifacts/JUnit-test-results-(Java-17)"
```

**Comment by EnricoMi** [comment]
Interestingly, your log above says

    Artifact JUnit_test_results_(Java_17) was downloaded to /home/runner/work/XXX/XXX/artifacts/JUnit test results (Java 17)

and further down it says

    Run ls -R
    Unit_test_results_(Java_17)

Are there whitespaces in the directory under `artifacts` or not?

**Comment by uli-f** [comment]
> Is this in a private repository?

Yes, it is. That makes debugging probably a bit more laborious.

**Comment by uli-f** [comment]
> Maybe `**` has a problem with the whitespaces in the path, can you also try to add this step before the publish action, please?
> 
> ```yaml
> - run: |
>     mv -v "artifacts/JUnit test results (Java 17)" "artifacts/JUnit-test-results-(Java-17)"
> ```

Good idea.
I removed the whitespace for now by replacing spaces with hyphens. We can always introduce the whitespace again once it works and then figure out how and where to properly escape it.

**Comment by uli-f** [comment]
So here are the results of some configurations:

1) Config 1
actions/upload-artifact@v3
```
- name: Upload JUnit Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: JUnit-test-results-(Java-${{ matrix.java }})
        path: build/test-results/test
```
EnricoMi/publish-unit-test-result-action@v1
```
- name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/TEST-*.xml"
          check_name: "JUnit Test Results"
          comment_mode: create new
          test_changes_limit: 30
          fail_on: "errors"
```
**Result** (excerpts):
Download artifacts:
`Artifact JUnit-test-results-(Java-17) was downloaded to /home/runner/work/XXX/XXX/artifacts/JUnit-test-results-(Java-17)`
Display structure of downloaded files:
`./JUnit-test-results-(Java-17)`
Echo download path:
`/home/runner/work/XXX/XXX/artifacts`
