### ISSUE TITLE
Add Support for the TRX Test Output Format

### ISSUE THREAD

**Issue by RehanSaeed** [EnricoMi/publish-unit-test-result-action#279]
The TRX test output format is popular in the .NET space and is backed by Microsoft.

The following similar project supports TRX format:
https://github.com/dorny/test-reporter

**Comment by EnricoMi** [comment]
Yes, there are a few test output formats that could be incorporated into this action.

**Comment by EnricoMi** [comment]
@RehanSaeed please give this a try:

```yaml
uses: EnricoMi/publish-unit-test-result-action/composite@branch-add-trx
with:
    trx_files: "**/*.trx"
```
