### ISSUE TITLE
NUNit input reports 1 test / 1 file / 1 suite despite there being 23 tests

### ISSUE THREAD

**Issue by clicketyclackety** [EnricoMi/publish-unit-test-result-action#329]
First of all, apologies that this is a private repo, but I hope the info I provide is enough to work with. As it's a private repo, I've redacted some info, but that shouldn't affect anything.
I have started trying to use the new NUnit parsing with a test suite I have. 

## Yaml run log (with DEBUG on)
[publish.log](https://github.com/EnricoMi/publish-unit-test-result-action/files/9113316/publish.log)
Please let me know if there is any info i should retract in here.

## Yaml Usage

``` yaml usage
# v2 offers NUnit support - https://github.com/EnricoMi/publish-unit-test-result-action/tree/devel-2.0
- name: Publish Integrated Unit Test Results
uses: EnricoMi/publish-unit-test-result-action@v2
if: ${{ always() }}
with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  check_name: Integrated Unit Test Results
  check_run_annotations: all tests, skipped tests
  comment_mode: always
  test_changes_limit: 999
  nunit_files: |
    MyProject/bin/x64/**/net48/*integrated_out.xml
  report_individual_runs: true
  root_log_level: DEBUG
  log_level: DEBUG
```

## Input NUnit file
Renamed to .txt so Github will alow uploading
[MyProject_integrated_out.xml.txt](https://github.com/EnricoMi/publish-unit-test-result-action/files/9113339/MyProject_integrated_out.xml.txt)

## Report
![image](https://user-images.githubusercontent.com/28632338/179021434-b1b309ee-3e1a-435f-936c-81a02f800b2e.png)
