### ISSUE TITLE
The published test results comment has an incorrect duration

### ISSUE THREAD

**Issue by tarundev-archa** [EnricoMi/publish-unit-test-result-action#342]
The published test results comment has an incorrect duration.

Below is YAML config:

```yaml
- name: Publish Test Results
  uses: EnricoMi/publish-unit-test-result-action@v2.0.0
  id: test-results
  if: always()
  with:
    junit_files: "test-results/**/*.xml"
    pull_request_build: "commit"
    time_unit: "seconds"

- name: Title
  run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).title }}"

- name: Summary
  run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).summary }}"
```

Below is the current test result comment, the duration shown is 4s but the actual duration is more than 5m.
## Test Results
2 885 tests   2 740 [:heavy_check_mark:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "passed tests")  4s [:stopwatch:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "duration of all tests")
   323 suites     145 [:zzz:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "skipped / disabled tests")
   323 files           0 [:x:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "failed tests")

Results for commit 6f76f203.

[test-results]:data:application/gzip;base64,H4sIABdL82IC/12MTQ7CIBgFr9KwdsE/H17GIIWE2BZDYdV4d6FqIC5n3sscyIfF7eg6McouE9pLyAPOJZkc4lYFr1in3EYKIH5424u1zSmOu3uEZ3WE95s3Yamqf1xKMX1NKtvQbfSX/aixepohevLYtHFdQ66ApFfSU8yEcxy0BAcMtNZu1uQOXGAAYpSnFr3eXd0pSA8BAAA=

:recycle: This comment has been updated with latest results.

I also generated the JSON output to review the results, I have added the `title` and `summary` output below.
`title:` All 2 740 tests pass, 145 skipped in 4s

`summary:` 2 885 tests  ±0   2 740 [:heavy_check_mark:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "passed tests") ±0   4s [:stopwatch:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "duration of all tests") ±0s

To reproduce the issue - I have attached the `test-results.zip` file which contains the same JUnit XML files I used to publish the result.
[test-results.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/9297186/test-results.zip)
