### ISSUE TITLE
No access to non-mounted directories

### ISSUE THREAD

**Issue by elesel** [EnricoMi/publish-unit-test-result-action#353]
Would you please update the documentation to reflect which directories the action will have access to when running from Docker? I was trying to specify `junit_files` like this:

```yaml
- name: Publish test results
  uses: EnricoMi/publish-unit-test-result-action@v2
  if: always()
  with:
    check_name: Test Results for ${{ github.workflow }}
    junit_files: ${{ runner.temp }}/pytest-reports/**/*.xml
```

but GitHub only provides a few volume mounts, and `${{ runner.temp }}` isn't covered by them. I moved the files to a relative directory and this is working fine, but I had to debug a bit to reach this conclusion. FWIW here are the relevant `docker run` command line options that GitHub uses to launch this action:

```
--workdir /github/workspace
-v "/var/run/docker.sock":"/var/run/docker.sock"
-v "/home/runner/work/_temp/_github_home":"/github/home"
-v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
-v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands"
-v "/home/runner/work/<repo_name>/<repo_name>":"/github/workspace"
```

You could even go so far as to fail the action if any of the `*_files` args attempt to reference anything not under the four mounted directories.
