### ISSUE TITLE
Make reporting GHA step fail when test results contain failure

### ISSUE THREAD

**Issue by atsu85** [EnricoMi/publish-unit-test-result-action#375]
# Current situation
When GHA step that produces test results exits with exit code 0, then GHA step that reports test failures with this action won't be marked as failed either even if test reports contain errors (it only generated failing check outside that job with test report).

At first glance fail_on: "test failures" ([Options related to reporting test results](https://github.com/EnricoMi/publish-unit-test-result-action#configuration)) seemed to do just what i wanted, but it
> Configures the state of the **created test result check** run

and it isn't about the GHA step that uses this action.

# Expected situation
When there are test failures, then regardless of exit code of the GHA step that generated test report, GHA step that uses this action should be marked as failed. This would prevent running following steps and jobs when there are test failures, but exit code is 0.

For backwards compatibility it might make sense to add new option that changes this behaviour

# My current workaround

Currently my workaround was to just start using different GHA that fails the reporting GHA step when there are test failures (i've highlighted bellow the reason why exit code for test result is always 0 - my self-hosted GHA runner can't use sudo to change generated reports ownership so i do it in container after running tests):

![image](https://user-images.githubusercontent.com/1206512/202180948-b77c8116-5aad-4064-939a-cd249939e269.png)

**Comment by EnricoMi** [comment]
You can access the test results via [JSON output](https://github.com/EnricoMi/publish-unit-test-result-action#json-result) (see example in `Access JSON via step outputs`):

```yaml
- name: Publish Test Results
  uses: EnricoMi/publish-unit-test-result-action@v2
  id: test-results
  if: always()
  with:
    junit_files: "test-results/**/*.xml"

- name: Conclusion
  run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
```

You can run / skip / fail subsequent steps depending on the value of `conclusion`:

```yaml
- name: Stop on test failures
  if: fromJSON( steps.test-results.outputs.json ).conclusion != "success"
  shell: bash
  run: false
```

Command `false` is equivalent to `exit 1`.
