### ISSUE TITLE
Can the action include an option to extract files?

### ISSUE THREAD

**Issue by laeubi** [EnricoMi/publish-unit-test-result-action#397]
Currently as described in the docs one needs the following [workflow to support PR](https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches)s:

```yaml
    steps:
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
           mkdir -p artifacts && cd artifacts

           artifacts_url=${{ github.event.workflow_run.artifacts_url }}

           gh api --paginate "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
           do
             IFS=$'\t' read name url <<< "$artifact"
             gh api $url > "$name.zip"
             unzip -d "$name" "$name.zip"
           done

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          junit_files: "artifacts/**/*.xml"
```

this is quite clumsy and of course if something changes this requires users to update all there scripts by hand.

I therefore wondering if the extraction part can be added as part of the action itself, so one ends up with the following:

```yaml
    steps:
       - name: Extract and Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          token:  ${{secrets.GITHUB_TOKEN}}
          extract: true
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          junit_files: "artifacts/**/*.xml"
```

this will greatly reduce the clutter needed to setup a PR enabled workflow.

**Comment by EnricoMi** [comment]
I agree, that first step is not great and hard to maintain.

The nice thing about actions is they do very specific things, while they can be combined with other actions doing their specific thing. So the first step should rather be an action itself. It is merely there because the [download-artifact](https://github.com/actions/download-artifact/) action cannot download artifacts from a different workflow. Ideally, that action should be used to feed artifacts into the publish actions. And it is capable of extracting those artifacts (as it is its core use case).

Either that feature should go into that action (and have more users benefit from it), or a different action that is capable should be used there.

Test result files are usually created as plain files in some directory. So the extraction does not seem test-result specific, but github artifact centered. What do you think?

**Comment by laeubi** [comment]
> So the extraction does not seem test-result specific, but github artifact centered. What do you think?

At laest (until now) I only have seen this for the test results, but you are right that this could a a generic one.

so if you have an idea how to enhance the download-artifact action it would be good to suggest what is required to use it with this action in combination :+1:

**Comment by EnricoMi** [comment]
Looks like that feature is the longest outstanding feature of [download-artifact](https://github.com/actions/download-artifact/), annoying:
https://github.com/actions/download-artifact/issues/3
https://github.com/actions/download-artifact/issues/60
https://github.com/actions/download-artifact/issues/172

**Comment by infogulch** [comment]
It turns out there is a github action that can download files from another workflow: https://github.com/dawidd6/action-download-artifact

It would be very nice if this action could also publish all the matched results files as an artifact to enable other workflows to download and use.

**Comment by EnricoMi** [comment]
Thanks for the pointer to that download action.

Again, uploading files is not test-result-specific but a generic Github operation. The existing Github action `actions/upload-artifact` should be used, rather than replicating and maintaining that feature here.

```yaml
- name: Download and Extract Artifacts
  uses: dawidd6/action-download-artifact@v2
  with:
    run_id: ${{ github.event.workflow_run.id }}
    path: artifacts

- name: Upload test results
  uses: actions/upload-artifact@v3
  with:
    name: test-results
    path: artifacts/**/*.xml
```
