### ISSUE TITLE
Can the action include the steps to create a badge?

### ISSUE THREAD

**Issue by laeubi** [EnricoMi/publish-unit-test-result-action#398]
As [described in the docs](https://github.com/EnricoMi/publish-unit-test-result-action#create-a-badge-from-test-results) one can generate a badge for the test what is a really cool feature!

Sadly the setup is very complex and error prone, I therefore wonder if the action can be enhanced to include the required shellscripts and action from the current

```yaml
steps:
- …
- name: Publish Test Results
  uses: EnricoMi/publish-unit-test-result-action@v2
  id: test-results
  if: always()
  with:
    junit_files: "test-results/**/*.xml"

- name: Set badge color
  shell: bash
  run: |
    case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
      success)
        echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
        ;;
      failure)
        echo "BADGE_COLOR=800000" >> $GITHUB_ENV
        ;;
      neutral)
        echo "BADGE_COLOR=696969" >> $GITHUB_ENV
        ;;
    esac

- name: Create badge
  uses: emibcn/badge-action@d6f51ff11b5c3382b3b88689ae2d6db22d9737d1
  with:
    label: Tests
    status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
    color: ${{ env.BADGE_COLOR }}
    path: badge.svg

- name: Upload badge to Gist
  # Upload only for master branch
  if: >
    github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'master' ||
    github.event_name != 'workflow_run' && github.ref == 'refs/heads/master'
  uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
  with:
    token: ${{ secrets.GIST_TOKEN }}
    gistURL: https://gist.githubusercontent.com/{user}/{id}
    file: badge.svg
```

to something like this:

```yaml
steps:
- …
- name: Publish Test Results and generate badge
  uses: EnricoMi/publish-unit-test-result-action@v2
  id: test-results
  if: always()
  with:
    junit_files: "test-results/**/*.xml"
    badge_branch: 'master'  # this enables generation, but on master branch only
    badge_token: ${{ secrets.GIST_TOKEN }}
    badge_file: 'badge.svg'
    badge_url: https://gist.githubusercontent.com/{user}/{id}
    badge_label: Tests
```

this will greatly reduce the amount of setup and maintenance and is less error prone.
