### ISSUE TITLE
The PR comment does not contain sections with list of added/removed tests

### ISSUE THREAD

**Issue by pavel-spacil** [EnricoMi/publish-unit-test-result-action#406]
Hi, I'm using this action to report test results from two test rounds (JUnit, unit + integration tests), the values in PR comment seem to be correct but the expandable sections with added/removed tests are missing even though PR is adding/removing tests.

I'm using the latest version of the action with pretty standard configuration:

```yaml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          junit_files: "**/build/test-results/*/*.xml"
```

Debug logs show that it found all the XML files with the results and near the end that it read the annotation from default branch build with all test names. No more clues in debug log why the diff was not created.
