### ISSUE TITLE
Composite action pip deprecations

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#409]
When using the composite action:
```yaml
      - name: "Publish 'Instrumentation Results ${{ matrix.android-api }}' check suite."
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          check_name: '🔔 Test: Instrumentation Results ${{ matrix.android-api }}'
          comment_mode: off
          report_individual_runs: true
          test_changes_limit: 0
          junit_files: ${{ github.workspace }}/**/build/outputs/androidTest-results/connected/flavors/debugAndroidTest/TEST-*.xml
```

I get this warning 3 times for `wrapt`, `lxml`, `future`:

> DEPRECATION: wrapt is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Example run: https://github.com/TWiStErRob/net.twisterrob.libraries/actions/runs/4274619957/jobs/7441366151#step:6:124

Note: this does not cause any issues right now, just an FYI (I couldn't find a similar issue tracking this).
