### ISSUE TITLE
503 Service Unavailable when fetching the package

### ISSUE THREAD

**Issue by MattBro** [EnricoMi/publish-unit-test-result-action#423]
This morning starting at 9:48 EDT we are seeing the following error:

![image](https://user-images.githubusercontent.com/9833550/225354559-08c0f97d-3cb7-48ff-ae0d-acb1a23d4f8a.png)

On this line of our build yml:

```
- name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.16
        if: ${{ always() }}
        with:
          comment_mode: off
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: testresults/*.xml
````

We had a successful build at 9:43 EDT. So, seems to have started between 9:43 and 9:48 EDT. I'm not seeing failures with other github packages. So, it might have something to do with this specific package. But, I don't see any changes on this repo. Were there any settings changed or anything else that could cause this?

[This page
](https://github.com/users/EnricoMi/packages/container/package/publish-unit-test-result-action) won't load either:

![image](https://user-images.githubusercontent.com/9833550/225355788-d1dc95fe-c360-45bf-9026-ec6e38ca37f2.png)
