### ISSUE TITLE
Can't find the tests results

### ISSUE THREAD

**Issue by eduardafa** [EnricoMi/publish-unit-test-result-action#424]
I'm using this action to publish my test results. During the first tests, it worked using 'push' as a trigger to run my test workflow.

Below are the logs when the action was working.
![Screen Shot 2023-03-17 at 11 19 04 AM](https://user-images.githubusercontent.com/54603419/225924466-b592f421-a4af-4ff4-96cd-3ca448dde84c.png)

But after some time, without changing anything, the action stopped to show the test results. Below, I have the logs when the action runs.
![Screen Shot 2023-03-17 at 11 19 15 AM](https://user-images.githubusercontent.com/54603419/225924816-6ad7d62c-47c0-4b34-aee4-f03833fa16bf.png)

This is my code related to this action:
```yaml
- name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: ${{ success() || failure() }}
      with:
        files: |
          **/test-results.xml     
```

Edit: If I run my tests locally, I can find this path to the test results (test-results.xml).

What is happening here? Any suggests?
