### ISSUE TITLE
Warning: Request GET /search/issues?q=type... failed with 403: Forbidden

### ISSUE THREAD

**Issue by xec-abailey** [EnricoMi/publish-unit-test-result-action#426]
Been using this action for a while and noticed that I'm getting a few failed requests toward the end that I can't figure out the root cause of. 

![image](https://user-images.githubusercontent.com/73495852/226464743-6c9cdb7f-486c-47cb-88ef-1807e43d8fd7.png)

I'm using the publish-unit-test-result-action@v2 from within another custom action so I'm wondering if it has to do with inherited permissions or something. 

The main ci/cd workflow: 

```
testing-run-publish:
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses:sutom-test-publish-action@v2 #repo must be accessible to full org
        with:
          # some parameters
          ...
```

Then in the custom action I have the following: 

```
name: "Test and Publish"
description: "Run Pytest Integration Tests and Publish Results"
inputs: 
  image-name: 
    description: "Docker image name"
    required: true
  registry-username:
    description: "Docker registry username"
    required: true
  registry-password:
    description: "Docker registry password"
    required: true
  registry-url:
    description: "Docker registry"
    required: false
    default: "dataanalysis.azurecr.io"
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: "./Dockerfile"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      id: login
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

          # building test image locally only (no push) using the base image built in previous job
    - name: Build Testing Image
      if: inputs.build-context-target != ''
      uses: docker/build-push-action@v4.0.0
      with:
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        load: true # load image into local docker daemon
        pull: true
        push: false
        tags: testing:latest
        target: testing

    - name: Run Pytest Integration Tests
      shell: bash
      run: |
        docker run --mount type=bind,source=${{ runner.temp }},target=/temp --rm ${{ inputs.target }}:latest

    - name: Upload Pytest Results Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ${{ runner.temp }}/result.xml

    - name: Download Artifacts
      if: always()
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Publish Pytest Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: "artifacts/**/*.xml"
```

Is the checkout causing a permissions issue here or is this something else? 

Cheers!
