### ISSUE TITLE
unit tests as a consecutive GitHub action fail to publish results

### ISSUE THREAD

**Issue by CraigGabel** [EnricoMi/publish-unit-test-result-action#471]
I am trying to run 2 actions (see my yml file at the end of this write up)
1. Modify version numbers held in a source file
2. Run ceedling unit tests, and publish results with EnricoMi/publish-unit-test-result-action@v2 (note that we use a status check hold on PRs requiring this step to pass before merge)

a few things I've run into (I could be wrong with some of these)
1. The two workflows cannot run concurrently.  The version number bumping will cause a commit/push.  The unit tests and publish might work, but it is not happening on the HEAD of the branch and so the check will fail.
2. For the same reason as 1, if being run consecutively, the unit tests cannot be run before the version bumping
3. I do not want to run the version number bump on PR closed.  This would require access to commit directly to main, which I don't want to allow.  Nor do I want to run the version number bump on push, it would bump too frequently and require pulls from devs doing pushes to align with origin.
4. The unit tests and publish must be the last step in the PR process, or the GitHub status check fails.  (this is somewhat assumed, but partially tested)

This all results in me trying to run the 2 actions consecutively, with the version number bump happening first.  Everything works fine until the EnricoMi/publish-unit-test-result-action@v2 attempts to publish the results.  It is trying to publish the results against the original commit associated with the PR...the commit BEFORE the version number bump causes a commit/push.  In the attached screenshot, you can see the checkout for the unit tests correctly action happening on the new HEAD commit (the one created by the version bump action...you will have to just trust me that this is the correct commit), and the publish is attempted on the previous commit (again, you will have to trust me here...but you can at least see the SHAs are different).

Finally, the issue I am driving at (as described in the above paragraph).  If the unit tests are a consecutive action following an action that causes a commit/push, the publish fails as it tries to publish to a commit that is not the HEAD of the branch.  Can this be fixed?  If not, can someone think of other approaches to run both of these actions on my project?

Edit: A small side note.  I cannot use EnricoMi/publish-unit-test-result-action@v2 but must instead use v1.  Something wrong with the check receiving the publish, not sure and I don't remember specifics.  My screenshot show use of v2 while I was trying things, but I actually use v1 in my project.

Thanks

the yaml for my GitHub action

```yaml
name: my_yaml
on:
  pull_request:
    types:
      [opened, reopened]

jobs:
  update_version_number:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Update version.txt
        run: |
          [redacted 'sed' commands to modify files' version numbers]
      
      - name: setup for commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "helpme@noreply.org"
      
      - name: commit
        run: |
          git add [redacted file path]
          git commit -m "commit message"
          git push
  unit_tests:
    needs: [update_version_number]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1
      - name: Run tests
        uses: batov/ceedling_action@1.0.0
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: build/artifacts/test/report.xml
```
![publish fail](https://github.com/EnricoMi/publish-unit-test-result-action/assets/28834331/9afe12a1-dd3f-4a77-b416-45a82cb5d358)
