### ISSUE TITLE
action_fail_on_inconclusive passed with just a warning annotation

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#533]
I was expecting something red, at least in one place out of the below.

```
      - name: "Publish 'Integration Test Results' check run."
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: 'Integration Test Results'
          comment_mode: off
          report_individual_runs: true
          action_fail_on_inconclusive: true
          test_changes_limit: 0
          junit_files: outputs/junit.xml
```

<img width="938" alt="image" src="https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/6cb3803a-6490-447a-b3d9-61b096f67b4b">

<img width="1245" alt="image" src="https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/5fbb5a02-675d-484a-80bd-4be0e5601ba1">

<img width="1212" alt="image" src="https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/2851fb18-af5c-447e-b474-6d0a0f91eddc">
