### ISSUE TITLE
Support per file `test_file_prefix` 

### ISSUE THREAD

**Issue by troex** [EnricoMi/publish-unit-test-result-action#588]
It would nice if it would be setup individual `test_file_prefix` per each file. 

My use case is that I have multiple apps in a mono repository where each app has it's own directory and since all off them require same environment I do run tests for each of them in a single github job, as result I have 5 junit xml files but they are all prefixed with local relative path so in order to get annotations to show up properly I have to setup `publish-unit-test-result-action`  5 times like:

```
      - name: Publish RSpec Results (APP 1)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: 'RSpec / APP 1'
          comment_mode: errors
          test_file_prefix: "+app_1/"
          files: |
            test-results/rspec/app_1.xml

      - name: Publish RSpec Results (APP 2)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: 'RSpec / APP 2'
          comment_mode: errors
          test_file_prefix: "+app_2/"
          files: |
            test-results/rspec/app_2.xml
# ... and so on
```

This works but not optimal, and I have 5 annotations instead of one.

I also tried to change how my junit reporter (formatter) works but it was not something it's easy achievable there (ruby, rspec + rspec_junit_formatter)
