### ISSUE TITLE
Feature Request: Add "regression" option to `fail_on` parameter

### ISSUE THREAD

**Issue by Alexgar24** [EnricoMi/publish-unit-test-result-action#624]
Hello,

Thank you for developing the `publish-unit-test-result-action`; it's greatly enhancing our CI workflows.

### Feature Request:

Please add a "regression" option to the `fail_on` parameter.

### Use Case:

In our project, some tests are currently failing, and we're working on fixing them. We want the action to fail only if new test failures are introduced compared to the previous commit. This helps us catch regressions without being hindered by existing failures.

### Note:

Since the action already compares test results with the parent commit to display changes in the summary, implementing this feature might be straightforward.

### Example Usage:
```yml
- name: Publish Unit Test Results
  uses: EnricoMi/publish-unit-test-result-action@v2
  with:
    files: '**/test-results.xml'
    fail_on: 'regression'
```

### Expected Behavior:

The action fails the workflow if the number of test failures or errors has increased compared to the parent commit.
If the number of failures has decreased or remained the same, the workflow passes.
Thank you for considering this feature!

Best regards,

Álex
