### ISSUE TITLE
The latest MacOS-14 vm-image provided by github at the time of this writing (22nd of October 2024) causes a cryptic python error

### ISSUE THREAD

**Issue by ksidirop-laerdal** [EnricoMi/publish-unit-test-result-action#633]
I have the following simple yaml:

```yaml
jobs:
  
  build:

    runs-on: 'macos-14'

    [...]

      - name: '📡 Publish Test Results' # https://github.com/marketplace/actions/publish-test-results
        uses: 'EnricoMi/publish-unit-test-result-action/macos@v2'
        if: always()
        with:
          files: |
            TestResults/**/TEST-*.xml
            TestResults/**/TEST-*.trx
```

This used to work up until a few days ago just fine but it now results in the following cryptic error:

```
 src/c/_cffi_backend.c:6121:9: error: call to undeclared function '_PyErr_WriteUnraisableMsg'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                _PyErr_WriteUnraisableMsg(PyText_AS_UTF8(s), NULL);
                ^
        src/c/_cffi_backend.c:6121:9: note: did you mean 'PyErr_WriteUnraisable'?
        /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/pyerrors.h:233:18: note: 'PyErr_WriteUnraisable' declared here
        PyAPI_FUNC(void) PyErr_WriteUnraisable(PyObject *);
                         ^
        1 warning and 1 error generated.
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]
```

Any insights appreciated.
