### ISSUE TITLE
Unexpected input(s) 'commit'

### ISSUE THREAD

**Issue by RyanSchw** [EnricoMi/publish-unit-test-result-action#64]
I'm running v1.6 and provided a git sha as shown in the README.

However, I get the following warning:
```
Warning: Unexpected input(s) 'commit', valid inputs are ['entryPoint', 'args', 'github_token', 'check_name', 'files', 'report_individual_runs', 'deduplicate_classes_by_file_name', 'hide_comments', 'comment_on_pr', 'log_level']
```

**Comment by EnricoMi** [comment]
Right, `commit` is an "undocumented" argument (though it is in the README). This is just a warning in the logs.

What is your use-case, maybe it is worth "documenting" it in the `actions.yml`.

**Comment by RyanSchw** [comment]
Ah, gotcha.

Well for use case I'm using [slash command dispatch](https://github.com/peter-evans/slash-command-dispatch) to dispatch some jest tests. The comment is made on the PR (you would actually comment `/test` on the PR), and want to report the results of the test. Since the test command is technically launched from a `repository_dispatch`, there's no reference to the PR I want to comment on. I got around this by adding the git sha (of the HEAD of the PR branch) to the `commit` argument so that way this publish package knew where to publish the reports.

This is the result:
![image](https://user-images.githubusercontent.com/32225075/101850859-920d2e00-3b28-11eb-841c-25598120f6d8.png)

I would be happy to post a simple example YAML of my workflow if that helps illustrate my example more.

**Comment by EnricoMi** [comment]
Very interesting use-case, please add an example YAML file to see how this all wires together (especially the commit sha).

**Comment by RyanSchw** [comment]
File that runs the jest tests:
```yaml
name: Run jest tests

on:
  repository_dispatch:
    types: [e2e-command]

jobs:
  test_local:
    needs: build_local
    runs-on: ubuntu-latest
    steps:
    # repository_dispatch doesn't have the correct $GITHUB_REF so we need to provide it
    # first, get the name of the branch from the PR
    - name: Github API Request
      if: github.event_name == 'repository_dispatch'
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.client_payload.github.payload.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # then, check it out
    - uses: actions/checkout@v2
      with:
        ref: ${{ fromJson(steps.request.outputs.data).head.ref }}

    - name: Set up Node.js v13
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Node install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run tests
      run: |
        npm run serve &
        npm test ${{ github.event.client_payload.slash_command.args.unnamed.all }}

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: github.event_name == 'repository_dispatch'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: test/results/*.xml
        report_individual_runs: true
        commit: ${{ fromJson(steps.request.outputs.data).head.sha }}
```

Dispatch file:
```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          commands: |
            e2e
```

Then, in a PR, you can comment `/e2e xxx` to run `npm test xxx`.
