### ISSUE TITLE
Test results are reported on the wrong workflow

### ISSUE THREAD

**Issue by provegard** [EnricoMi/publish-unit-test-result-action#655]
I have two workflows in separate files:

* PR build - backend
* PR build - frontend

Each of the workflows contains a single job, `build_and_test`.

Both workflows are triggered on pull requests. They contain, respectively:

```
      - name: Backend test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Test Results (backend)"
          ignore_runs: true
          files: |
            build/test-reports/*.trx
```

and

```
      - name: Frontend test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Test Results (frontend)"
          ignore_runs: true
          files: |
            build/test-reports/jest/**/*.xml
```

When the frontend test workflow finishes, I see:

![Image](https://github.com/user-attachments/assets/010cb6b6-6bd5-4f15-a385-e710b11681e5)

When the backend test workflow finishes, I see:

![Image](https://github.com/user-attachments/assets/59a1834b-a179-4098-8d22-94cd7d3c234b)

It is unclear to me why "Test Results (frontend)" is added to the backend workflow and not the frontend workflow. Is there any additional option I need to set?

Thanks!
