### ISSUE TITLE
Customizable Pass Percentage to Determine Pipeline Success

### ISSUE THREAD

**Issue by konstantinoskolios** [EnricoMi/publish-unit-test-result-action#671]
Is it possible to check the **percentage** of `passed/failed` tests and allow the user to define a threshold for considering the pipeline successful?

For `example`: after generating the test results, we want to pass at least 80% of the tests. If this threshold is met, the pipeline should be marked as successful so we can proceed with merging to `master`.

**Comment by EnricoMi** [comment]
You should be able to easily implement that logic in your Workflow using the JSON output.
https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#json-result

Something like this:
```yaml
- name: Test success ratio
  env:
    TESTS: ${{ fromJSON( steps.test-results.outputs.json ).stats.tests }}
    PASSES: ${{ fromJSON( steps.test-results.outputs.json ).stats.tests_succ }}
    THRESHOLD: 80
  run: |
    RATIO=$(( PASSES * 100 / TESTS ))
    echo "Test success ratio is ${RATIO}%"
    [ $RATIO -ge $THRESHOLD ]
  shell: bash
```
