### ISSUE TITLE
Documentation on token

### ISSUE THREAD

**Issue by eblot** [EnricoMi/publish-unit-test-result-action#69]
Sorry to bother with a so stupid question, but what are the expected permissions for the `GITHUB_TOKEN`?
I registered a new token with `repo` and `workflow`, but it does not seem to do the job:

The token seems to be used:
```
Run EnricoMi/publish-unit-test-result-action@v1.6
  with:
    github_token: ***
    files: build_report.xml
    check_name: Unit Test Results
    hide_comments: all but latest
    comment_on_pr: true
    log_level: INFO
```
but GitHub complains with
```
github.GithubException.GithubException: 403 {"message": "You must authenticate via a GitHub App.", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"} 
```
Should -I- register this app myself? I'm a bit lost.
Thanks.
