### ISSUE TITLE
xUnit tests outputted in JUnit format display only as runs and not tests

### ISSUE THREAD

**Issue by clicketyclackety** [EnricoMi/publish-unit-test-result-action#91]
Is this expected behaviour or am I potentially doing something wrong?

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          check_run_annotations: all tests, skipped tests
          comment_on_pr: true
          test_changes_limit: 5
          hide_comments: all but latest
          files: Release/net472/virtual_out.xml
          report_individual_runs: true

**Comment by EnricoMi** [comment]
Can you provide me a screenshot or a link to the PR comment?

**Comment by EnricoMi** [comment]
Interesting, please send me the xml file so I can reproduce it.

**Comment by clicketyclackety** [comment]
Github only supports uploading txts so you'll have to rename the extension back to .xml 😉

[virtual_out.txt](https://github.com/EnricoMi/publish-unit-test-result-action/files/6110093/virtual_out.txt)

**Comment by EnricoMi** [comment]
Please test the action from this branch: `branch-either-class-or-test-name`

```
  - name: Publish Unit Test Results
    uses: EnricoMi/publish-unit-test-result-action@branch-either-class-or-test-name
    with:
      ...
```

Btw, you can remove all default values from your config and reduce it as follows:

```
  - name: Publish Unit Test Results
    uses: EnricoMi/publish-unit-test-result-action@v1
    if: always()
    with:
      files: Release/net472/virtual_out.xml
```
